interface Tech {
  kor: string;
  eng: string;
}

type TechMajor = '기획' | '디자인' | '프론트엔드' | '백엔드' | '기타';

export const TECHS_BY_MAJOR: Record<TechMajor, Tech[]> = {
  기획: [
    { kor: 'Jira', eng: 'Jira' },
    { kor: '슬랙', eng: 'Slack' },
    { kor: '노션', eng: 'Notion' },
  ],
  디자인: [
    { kor: 'Adobe Illustrator', eng: 'Adobe Illustrator' },
    { kor: 'Adobe Photoshop', eng: 'Adobe Photoshop' },
    { kor: 'Figma', eng: 'Figma' },
  ],
  프론트엔드: [
    { kor: '리액트', eng: 'React.js' },
    { kor: '넥스트', eng: 'Next.js' },
    { kor: '뷰', eng: 'Vue.js' },
    { kor: '앵귤러', eng: 'Angular' },
    { kor: '타입스크립트', eng: 'TypeScript' },
    { kor: '자바스크립트', eng: 'JavaScript' },
    { kor: '리덕스', eng: 'Redux' },
    { kor: '리액트네이티브', eng: 'React Native' },
    { kor: '엑스포', eng: 'Expo' },
    { kor: '안드로이드', eng: 'Android' },
    { kor: '스위프트', eng: 'Swift' },
    { kor: 'HTML/CSS', eng: 'HTML/CSS' },
    { kor: 'Tailwind CSS', eng: 'Tailwind CSS' },
  ],
  백엔드: [
    { kor: '노드', eng: 'Node.js' },
    { kor: '익스프레스', eng: 'Express.js' },
    { kor: '스프링부트', eng: 'Spring Boot' },
    { kor: '스프링', eng: 'Spring' },
    { kor: '자바', eng: 'Java' },
    { kor: '코틀린', eng: 'Kotlin' },
    { kor: '파이썬', eng: 'Python' },
    { kor: '장고', eng: 'Django' },
    { kor: '플라스크', eng: 'Flask' },
    { kor: '루비온레일즈', eng: 'Ruby on Rails' },
    { kor: 'PHP', eng: 'PHP' },
    { kor: 'JPA', eng: 'JPA' },
    { kor: '하이버네이트', eng: 'Hibernate' },
    { kor: 'QueryDSL', eng: 'QueryDSL' },
    { kor: 'WebFlux', eng: 'Spring WebFlux' },
    { kor: 'OAuth2', eng: 'OAuth2' },
    { kor: 'JWT', eng: 'JWT' },
    { kor: 'SSE', eng: 'SSE' },
    { kor: 'MySQL', eng: 'MySQL' },
    { kor: 'PostgreSQL', eng: 'PostgreSQL' },
    { kor: 'MongoDB', eng: 'MongoDB' },
    { kor: 'Redis', eng: 'Redis' },
    { kor: 'SQLite', eng: 'SQLite' },
    { kor: 'MariaDB', eng: 'MariaDB' },
    { kor: 'OracleDB', eng: 'Oracle Database' },
    { kor: 'Firebase', eng: 'Firebase' },
    { kor: 'Supabase', eng: 'Supabase' },
    { kor: 'Elasticsearch', eng: 'Elasticsearch' },
    { kor: 'Kafka', eng: 'Apache Kafka' },
    { kor: 'RabbitMQ', eng: 'RabbitMQ' },
  ],
  기타: [
    { kor: '도커', eng: 'Docker' },
    { kor: '쿠버네티스', eng: 'Kubernetes' },
    { kor: 'AWS', eng: 'Amazon Web Services' },
    { kor: '애저', eng: 'Microsoft Azure' },
    { kor: '구글클라우드', eng: 'Google Cloud' },
    { kor: '깃허브액션', eng: 'GitHub Actions' },
    { kor: '젠킨스', eng: 'Jenkins' },
    { kor: 'GitLab CI', eng: 'GitLab CI/CD' },
    { kor: 'Cloudflare', eng: 'Cloudflare' },
    { kor: 'Vercel', eng: 'Vercel' },
    { kor: 'Gradle', eng: 'Gradle' },
    { kor: 'Maven', eng: 'Maven' },
    { kor: 'Nginx', eng: 'Nginx' },
    { kor: 'gRPC', eng: 'gRPC' },
    { kor: 'Terraform', eng: 'Terraform' },
    { kor: 'Ansible', eng: 'Ansible' },
    { kor: 'Linux', eng: 'Linux' },
    { kor: '깃', eng: 'Git' },
    { kor: '깃허브', eng: 'GitHub' },
    { kor: 'JUnit 5', eng: 'JUnit 5' },
    { kor: 'Mockito', eng: 'Mockito' },
    { kor: 'OpenAPI/Swagger', eng: 'OpenAPI/Swagger' },
    { kor: 'Prometheus', eng: 'Prometheus' },
    { kor: 'Grafana', eng: 'Grafana' },
    { kor: 'Logstash', eng: 'Logstash' },
    { kor: 'Kibana', eng: 'Kibana' },
    { kor: 'GraphQL', eng: 'GraphQL' },
    { kor: 'WebSocket', eng: 'WebSocket' },
    { kor: 'C언어', eng: 'C' },
    { kor: 'C++', eng: 'C++' },
  ],
};
